version: '3.8'

services:
  ai-restaurant-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - APP_NAME=AI餐厅推荐系统
      - DEBUG=False
    volumes:
      - ./backend:/app
    restart: unless-stopped 